# fly.toml app configuration file generated for ntfy-app on 2023-09-20T20:40:23-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ntfy-app"
primary_region = "scl"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[[mounts]]
  source = "ntfy_volume"
  destination = "/app/data"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
